Update e2e.yaml

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -1,30 +1,25 @@
-name: E2E tests
-
-on:
-  workflow_dispatch:
-  workflow_call:
-    secrets:
-      access-token:
-        required: true
+name: My workflow
+on: push
 
 jobs:
-  e2e-tests:
+  my-first-job:
     runs-on: ubuntu-latest
     steps:
-      - name: Print github owner and repo
+      - name: Hello
+        run: echo "Hello world"
+
+  my-second-job:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Bye
+        run: echo "Bye world"
+
+  failed-job:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed
         run: |
-          echo "Github owner and repo: ${{ github.repository }}"
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          repository: udemy-lauromueller/github-actions-course-example-e2e
-          ref: main
-          token: ${{ secrets.access-token || secrets.GITHUB_TOKEN }}
-      - name: Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: '20.x'
-      - name: Install dependencies
-        run: npm ci
-      - name: Run E2E tests
-        run: npm run test:e2e
+          echo "I am failed"
+          exit 1
+      - name: Couldn't Run
+        run: echo "Earlier failure"
